### ISSUE TITLE
Undefined function 'gcp' for input arguments of type 'char'

### ISSUE THREAD

**Issue by SarviD** [eeglabdevelopers/eeglab#398]
### Description

I want to precompute the power spectrum for the channel measures in a study design and I received the following error of " Undefined function 'gcp' for input arguments of type 'char' "

<br>
#### Steps to Reproduce

1. Load existing study
2. Study > precompute channel measures > list of measures to compute > power spectrum

<br>
#### Expected behavior:
I want to compute the difference of theta power in two different conditions and plot the topographies with the statistics calculations.

<br>
#### Actual behavior:
I can not compute the channel measures because of the error!

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 Pro 64-bit operating system, x64-based processor|
| Matlab version | R2020b |
| EEGLAB version |V2021.1 |

**Comment by cll008** [comment]
Hi there, does the error tell you which file and line number the error occurs?
This may be related to #383, please also try using the develop version of EEGLAB (or overwriting `std_precomp` with the [latest version](https://github.com/sccn/eeglab/blob/develop/functions/studyfunc/std_precomp.m).

**Comment by SarviD** [comment]
Hello, 

Thank you for your reply. 
I attached a screen shot of the error so you can take a look. 

Even though I tried the previous version of the eeglab and it worked. 

kind regards, 
Sarvenaz PIRONNEAU-DANESHGAR 
PhD candidate - EXECO (EXercice, SEnsorimotricite, COgnition) Research Team 
Office Number : R.09 - Tel : 05.49.45.46.82 
Centre de Recherches sur la Cognition et l’Apprentissage (CeRCA) 
Université de Poitiers - UMR CNRS 7295

**Comment by arnodelorme** [comment]
I believe this was fixed recently, but it is not in the released zip version yet.

**Comment by cll008** [comment]
@sarviD I don't see a screenshot could you please try sharing again? And did you try replacing std_precomp?
@arnodelorme yes most likely. Although when revisiting #383 I noticed our fix wasn't complete (see PR #399 for additions)

**Comment by SarviD** [comment]
Hello 

Here is the screenshot. 

Have a nice day! 

Sarvenaz PIRONNEAU-DANESHGAR 
PhD candidate - EXECO (EXercice, SEnsorimotricite, COgnition) Research Team 
Office Number : R.09 - Tel : 05.49.45.46.82 
Centre de Recherches sur la Cognition et l’Apprentissage (CeRCA) 
Université de Poitiers - UMR CNRS 7295

**Comment by cll008** [comment]
@SarviD I still don't see it. Could you please check the thread on github, maybe email is blocking attachments for some reason. 

Thank you and wishing you a nice day as well.

**Comment by helentobback** [comment]
I get the same error when wanting to estimate the model parameters. I use the 2023 Matlab version. Is there any more help on how  I can fix this?

**Comment by arnodelorme** [comment]
Can you update your version of EEGLAB. This is something we experienced in older versions.

**Comment by helentobback** [comment]
The error continues to show up, even after the update

**Comment by helentobback** [comment]
> Can you update your version of EEGLAB. This is something we experienced in older versions.

I would like to add the next: in my command window the first error appearing is the next

Unrecognized field name "cellArray".
File C:\(myfilepath)\functions\popfunc\pop_loadset.m at line 301
File C:\(myfilepath)\functions\popfunc\pop_loadset.m at line 169
File C:\(myfilepath)\plugins\LIMO4.0\limo_batch_design_matrix.m at line 24
File C:\(myfilepath)\plugins\LIMO4.0\external\psom\psom_run_job.m at line 214
File C:\(myfilepath)\plugins\LIMO4.0\external\psom\psom_run_job.m at line 128
File C:\(myfilepath)\plugins\LIMO4.0\external\psom\psom_run_script.m at line 437
File C:\(myfilepath)\plugins\LIMO4.0\external\psom\psom_run_script.m at line 323
File C:\(myfilepath)\plugins\LIMO4.0\external\psom\psom_pipeline_process.m at line 591
File C:\(myfilepath)\plugins\LIMO4.0\external\psom\psom_run_pipeline.m at line 417
File C:\Program Files\MATLAB\toolbox\matlab\lang\parallel_function.m at line 837
File C:\Program Files\MATLAB\toolbox\parallel\cluster\+parallel\+internal\+parfor\cppRemoteParallelFunction.m at line 53

I think the error from above is only a consequence from this very first error. There seems to be a problem with the loadset function. I hope this could possibly help you verify my current problem. 

Kind regards
Helen
